.TH STATUS2SIGNAL "1" "2021" "NNB" "User Commands"
.SH NAME
STATUS2SIGNAL \- Status code to signal name converter
.SH SYNOPSIS
.B status2signal STATUSCODES
.SH DESCRIPTION
STATUS2SIGNAL is a tool to convert status code to signal name.
.SH REPORTING BUGS
Report bugs to https://github.com/NNBnh/status2signal/issues
