.TH STATUS2SIGNAL "1" "2021" "INFO MONO" "User Commands"
.SH NAME
STATUS2SIGNAL \- Status code to signal name translate
.SH SYNOPSIS
.B status2signal STATUSCODES
.SH DESCRIPTION
STATUS2SIGNAL is a tool to translate status code to signal name.
.SH REPORTING BUGS
Report bugs to https://github.com/info-mono/status2signal/issues
